export const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";
export const ADD_MEDICAL_HIST_SUCCESS = "ADD_MEDICAL_HIST_SUCCESS";
