export const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";
export const ADD_MEDICAL_HIST_SUCCESS = "ADD_MEDICAL_HIST_SUCCESS";
export const LOAD_ANTRIAN_SUCCESS = "LOAD_ANTRIAN_SUCCESS";
export const ADD_ANTRIAN_SUCCESS = "ADD_ANTRIAN_SUCCESS";
export const ANTRIAN_WAS_ENDS = "ANTRIAN_WAS_ENDS";
